class Message:
    """
    To store the messages
    """
    USER_ALREADY_EXISTS = "User with details provided already exists"
    INTERNAL_SERVER_ERROR = "Internal server error."
    INVALID_USERNAME = "Invalid username"
    USER_NOT_FOUND = "User not found"
    WRONG_PASSWORD = "Wrong password"
    WRONG_CREDENTIALS = "Wrong credentials supplied"
    BLOGGER_REGISTERED = "Blogger registered successfully!"
    NO_COMMENT_FOUND = "No comment present for this blog!"
    SUCCESSFUL_POST = "Posted successfully!"
    FAILURE_IN_POST = "Could not post the content."
    COULD_NOT_COMMENT = "Could not add comment to the blog."
    RESOURCE_NOT_FOUND = "Resource request does not exist."
    OPERATION_NOT_ALLOWED = "Operation not allowed."
    SUCCESSFUL_UPDATE = "Resource updated successfully."
    SUCCESSFUL_REMOVAL = "Resource removed successfully."
    FAILURE_IN_UPDATE = "Failed to update resource."
    FAILURE_IN_REMOVAL = "Failed to remove the resource."
    SIGNED_OUT = "Successfully signed out."
    COULD_NOT_FETCH = "Could not fetch the required data."
    COULD_NOT_INSERT = "Could not insert the required data."
    COULD_NOT_COMPLETE = "Could not complete the request."
