version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_USERNAME: example_user
      DB_PASSWORD: example_password
      DB_NAME: blogging
      # Add other environment variables as needed
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
